name: Deploy to EC2

on:
  push:
    branches:
      - naster

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@<EC2_PUBLIC_IP> << 'EOF'
          docker pull reemnu26/simple-java-maven-app:latest
          CONTAINER_ID=$(docker ps -q --filter ancestor=reemnu26/simple-java-maven-app:latest)
          if [ -n "$CONTAINER_ID" ]; then
            docker stop $CONTAINER_ID
            docker rm $CONTAINER_ID
          fi
          docker run -d -p 80:80 reemnu26/simple-java-maven-app:latest
        EOF
